// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vrnvgasu/gophprofile/internal/handler (interfaces: App)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock.go -package=mocks . App
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/vrnvgasu/gophprofile/internal/model"
	avatar "github.com/vrnvgasu/gophprofile/internal/service/avatar"
	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockApp) Check(ctx context.Context) avatar.Health {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(avatar.Health)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockAppMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockApp)(nil).Check), ctx)
}

// Delete mocks base method.
func (m *MockApp) Delete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAppMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApp)(nil).Delete), ctx, id, userID)
}

// DeleteUserAvatar mocks base method.
func (m *MockApp) DeleteUserAvatar(ctx context.Context, userID, requesterID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserAvatar", ctx, userID, requesterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserAvatar indicates an expected call of DeleteUserAvatar.
func (mr *MockAppMockRecorder) DeleteUserAvatar(ctx, userID, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserAvatar", reflect.TypeOf((*MockApp)(nil).DeleteUserAvatar), ctx, userID, requesterID)
}

// Download mocks base method.
func (m *MockApp) Download(ctx context.Context, id, size string) (*avatar.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, id, size)
	ret0, _ := ret[0].(*avatar.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockAppMockRecorder) Download(ctx, id, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockApp)(nil).Download), ctx, id, size)
}

// DownloadUserAvatar mocks base method.
func (m *MockApp) DownloadUserAvatar(ctx context.Context, userID, size string) (*avatar.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadUserAvatar", ctx, userID, size)
	ret0, _ := ret[0].(*avatar.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadUserAvatar indicates an expected call of DownloadUserAvatar.
func (mr *MockAppMockRecorder) DownloadUserAvatar(ctx, userID, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadUserAvatar", reflect.TypeOf((*MockApp)(nil).DownloadUserAvatar), ctx, userID, size)
}

// ListUserAvatars mocks base method.
func (m *MockApp) ListUserAvatars(ctx context.Context, userID string) ([]model.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserAvatars", ctx, userID)
	ret0, _ := ret[0].([]model.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserAvatars indicates an expected call of ListUserAvatars.
func (mr *MockAppMockRecorder) ListUserAvatars(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserAvatars", reflect.TypeOf((*MockApp)(nil).ListUserAvatars), ctx, userID)
}

// Metadata mocks base method.
func (m *MockApp) Metadata(ctx context.Context, id string) (*model.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata", ctx, id)
	ret0, _ := ret[0].(*model.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metadata indicates an expected call of Metadata.
func (mr *MockAppMockRecorder) Metadata(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockApp)(nil).Metadata), ctx, id)
}

// Upload mocks base method.
func (m *MockApp) Upload(ctx context.Context, userID, fileName string, data []byte) (*model.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, userID, fileName, data)
	ret0, _ := ret[0].(*model.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAppMockRecorder) Upload(ctx, userID, fileName, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockApp)(nil).Upload), ctx, userID, fileName, data)
}
