version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - errorlint
    - misspell
    - revive
    - unconvert
    - whitespace
  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
          - staticcheck
          - unused
        path: mocks/
      - linters:
          - errcheck
          - bodyclose
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vrnvgasu/gophprofile
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
