// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vrnvgasu/gophprofile/internal/repository (interfaces: AvatarStorage)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock.go -package=mocks . AvatarStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/vrnvgasu/gophprofile/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarStorage is a mock of AvatarStorage interface.
type MockAvatarStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarStorageMockRecorder
	isgomock struct{}
}

// MockAvatarStorageMockRecorder is the mock recorder for MockAvatarStorage.
type MockAvatarStorageMockRecorder struct {
	mock *MockAvatarStorage
}

// NewMockAvatarStorage creates a new mock instance.
func NewMockAvatarStorage(ctrl *gomock.Controller) *MockAvatarStorage {
	mock := &MockAvatarStorage{ctrl: ctrl}
	mock.recorder = &MockAvatarStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarStorage) EXPECT() *MockAvatarStorageMockRecorder {
	return m.recorder
}

// CreateAvatar mocks base method.
func (m *MockAvatarStorage) CreateAvatar(ctx context.Context, a *model.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvatar", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAvatar indicates an expected call of CreateAvatar.
func (mr *MockAvatarStorageMockRecorder) CreateAvatar(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvatar", reflect.TypeOf((*MockAvatarStorage)(nil).CreateAvatar), ctx, a)
}

// GetAvatar mocks base method.
func (m *MockAvatarStorage) GetAvatar(ctx context.Context, id string) (*model.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatar", ctx, id)
	ret0, _ := ret[0].(*model.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatar indicates an expected call of GetAvatar.
func (mr *MockAvatarStorageMockRecorder) GetAvatar(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatar", reflect.TypeOf((*MockAvatarStorage)(nil).GetAvatar), ctx, id)
}

// GetLastUserAvatar mocks base method.
func (m *MockAvatarStorage) GetLastUserAvatar(ctx context.Context, userID string) (*model.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastUserAvatar", ctx, userID)
	ret0, _ := ret[0].(*model.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastUserAvatar indicates an expected call of GetLastUserAvatar.
func (mr *MockAvatarStorageMockRecorder) GetLastUserAvatar(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastUserAvatar", reflect.TypeOf((*MockAvatarStorage)(nil).GetLastUserAvatar), ctx, userID)
}

// GetUserAvatars mocks base method.
func (m *MockAvatarStorage) GetUserAvatars(ctx context.Context, userID string) ([]model.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAvatars", ctx, userID)
	ret0, _ := ret[0].([]model.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAvatars indicates an expected call of GetUserAvatars.
func (mr *MockAvatarStorageMockRecorder) GetUserAvatars(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAvatars", reflect.TypeOf((*MockAvatarStorage)(nil).GetUserAvatars), ctx, userID)
}

// Ping mocks base method.
func (m *MockAvatarStorage) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockAvatarStorageMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockAvatarStorage)(nil).Ping), ctx)
}

// SaveThumbnails mocks base method.
func (m *MockAvatarStorage) SaveThumbnails(ctx context.Context, id string, thumbnails map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveThumbnails", ctx, id, thumbnails)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveThumbnails indicates an expected call of SaveThumbnails.
func (mr *MockAvatarStorageMockRecorder) SaveThumbnails(ctx, id, thumbnails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveThumbnails", reflect.TypeOf((*MockAvatarStorage)(nil).SaveThumbnails), ctx, id, thumbnails)
}

// SetProcessingStatus mocks base method.
func (m *MockAvatarStorage) SetProcessingStatus(ctx context.Context, id string, status model.ProcessingStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProcessingStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProcessingStatus indicates an expected call of SetProcessingStatus.
func (mr *MockAvatarStorageMockRecorder) SetProcessingStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProcessingStatus", reflect.TypeOf((*MockAvatarStorage)(nil).SetProcessingStatus), ctx, id, status)
}

// SoftDeleteAvatar mocks base method.
func (m *MockAvatarStorage) SoftDeleteAvatar(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteAvatar", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteAvatar indicates an expected call of SoftDeleteAvatar.
func (mr *MockAvatarStorageMockRecorder) SoftDeleteAvatar(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteAvatar", reflect.TypeOf((*MockAvatarStorage)(nil).SoftDeleteAvatar), ctx, id)
}

// Stop mocks base method.
func (m *MockAvatarStorage) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockAvatarStorageMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAvatarStorage)(nil).Stop))
}
