{{- $dsn := .Values.secrets.databaseURI }}
{{- if .Values.postgres.enabled }}
  {{- $dsn = printf "postgres://%s:%s@gophprofile-postgres:5432/%s?sslmode=disable" .Values.postgres.user .Values.postgres.password .Values.postgres.db }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: gophprofile-secrets
  labels:
    app: gophprofile
type: Opaque
stringData:
  DATABASE_URI: {{ $dsn | quote }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | quote }}
{{- if .Values.postgres.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
{{- end }}
